In [1]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [3]:
sent =[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [4]:
##Define vocab size
voc_size = 10000

In [5]:
one_hot_repres = [one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_repres

[[8063, 5940, 8303, 9182],
 [8063, 5940, 8303, 9241],
 [8063, 7967, 8303, 2540],
 [6565, 4089, 9808, 1599, 7066],
 [6565, 4089, 9808, 1599, 1828],
 [8819, 8063, 5953, 8303, 1251],
 [7201, 6533, 4863, 1599]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repres,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8063 5940 8303 9182]
 [   0    0    0    0 8063 5940 8303 9241]
 [   0    0    0    0 8063 7967 8303 2540]
 [   0    0    0 6565 4089 9808 1599 7066]
 [   0    0    0 6565 4089 9808 1599 1828]
 [   0    0    0 8819 8063 5953 8303 1251]
 [   0    0    0    0 7201 6533 4863 1599]]


In [12]:
#feature Representation
dim =10
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step


array([[[ 0.01666569, -0.00933522,  0.02836515, -0.00868978,
         -0.0065946 , -0.02562325, -0.018355  ,  0.00978292,
         -0.02796948, -0.00673429],
        [ 0.01666569, -0.00933522,  0.02836515, -0.00868978,
         -0.0065946 , -0.02562325, -0.018355  ,  0.00978292,
         -0.02796948, -0.00673429],
        [ 0.01666569, -0.00933522,  0.02836515, -0.00868978,
         -0.0065946 , -0.02562325, -0.018355  ,  0.00978292,
         -0.02796948, -0.00673429],
        [ 0.01666569, -0.00933522,  0.02836515, -0.00868978,
         -0.0065946 , -0.02562325, -0.018355  ,  0.00978292,
         -0.02796948, -0.00673429],
        [ 0.01429781,  0.03274418,  0.03338984, -0.03149724,
          0.03929431, -0.00350168, -0.01478752,  0.03878644,
         -0.0480387 ,  0.04859402],
        [-0.02737668, -0.00345862, -0.02092723,  0.02538851,
         -0.04430642,  0.03705936,  0.04038643, -0.03925803,
         -0.01320002, -0.03735245],
        [ 0.02899543, -0.04363264, -0.0207863 ,  0.0